---
- name: make sure utility stacks are running
  command: curl http://localhost:51678/v1/metadata
  register: ecs_info
  until: ecs_info.stdout.find("ContainerInstanceArn") != -1
  retries: 30
  delay: 10

- debug:
    msg: "{{ (ecs_info.stdout|from_json).ContainerInstanceArn }}"

- name: Get ec2 information
  action: uri
      method=GET
      status_code=200
      url="http://169.254.169.254/latest/dynamic/instance-identity/document" return_content=yes
  register: ec2_info

- name: trigger lambda    
  uri: 
    url: "{{ lookup('env','lambda_url') }}/{{ (ec2_info.content|from_json).instanceId }}"
    method: POST
    return_content: yes
    HEADER_Content-Type: "application/json"
    body: ' { "ContainerInstanceArn":"{{ (ecs_info.stdout|from_json).ContainerInstanceArn }}" } '