---
- name: make sure utility stacks are running
  command: curl http://localhost:51678/v1/metadata
  register: ecs_info
  until: ecs_info.stdout.find("ContainerInstanceArn") != -1
  retries: 30
  delay: 10

- debug:
    msg: "{{ (ecs_info.stdout|from_json).ContainerInstanceArn }}"

- name: trigger lambda    
  uri: 
    url: "{{ lookup('env','lambda_url') }}"
    method: POST
    return_content: yes
    HEADER_Content-Type: "application/json"
    body: ' { "ContainerInstanceArn":"{{ (ecs_info.stdout|to_json).ContainerInstanceArn }}" } '